inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'lib/monkey_patches.rb'

Style/HashSyntax:
  Enabled: false

# dealbreaker:
Style/TrailingCommaInLiteral:
  Enabled: false

# would require external library
Layout/IndentHeredoc:
  Enabled: false
