source ENV['GEM_SOURCE'] || "https://rubygems.org"

group :development, :test do
<% gems = @configs['required'] + (@configs['optional'] || []) -%>
<% maxlen = gems.map! {|gem| { 'gem' => gem['gem'], 'version' => gem['version'], 'length' => gem['gem'].length + (("', '".length if gem['version']) || 0) + gem['version'].to_s.length } }.map{|gem| gem['length']}.max -%>
<% gems.each do |gem| -%>
  gem '<%= gem['gem'] %>'<%= ", '#{gem['version']}'" if gem['version'] %>, <%= ' ' * (maxlen - gem['length']) %> :require => false
<% end -%>
end

if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion, :require => false
else
  gem 'puppet', :require => false
end

# vim:ft=ruby
