---
name: 🏷️ Pull Request Labeler

on:
  - pull_request_target

permissions: {}

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    if: github.repository_owner == 'voxpupuli' || github.repository_owner == 'OpenVoxProject'
    permissions:
      pull-requests: write
    steps:
      - uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d # v6.2.0
